  <table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td class=footer width="100%"><a class=footer href="privacypolicy.htm">Privacy Policy</a> | <a class=footer href="siteterms.htm">Site Terms</a> |
      <a class=footer href="sitemap.htm">Site Map</a></font></td>
  </tr>
  <tr>
    <td class="footerblack" width="100%">Access to this Website is subject to the terms and conditions in the Legal Notices.<br>
      Copyright © 2003, H<sub>2</sub>OFresh. All Rights Reserved. H<sub>2</sub>OFresh Privacy Policy.</td>
  </tr>
  </table>
