      <table border="0" width="600" cellspacing="0" cellpadding="0" background="images/bg-submenu.jpg">
        <tr>
          <td nowrap nowrap>&nbsp;
            <a class=submnubar href="school.htm">School of Home<br>
            &nbsp;&nbsp;&nbsp;Water Knowledge</a><td bgcolor="#FFFFFF"><img src width=1 height=1></td>

          <td nowrap nowrap>&nbsp;
            <a class=submnubar href="products.htm">Products<br>
            &nbsp;&nbsp;&nbsp;Catalogue</a><td bgcolor="#FFFFFF"><img src width=1 height=1></td>

          <td nowrap nowrap>&nbsp;
            <a class=submnubar href="replacements.htm">Replacements<br>
            &nbsp;&nbsp;&nbsp;&amp; Parts</a><td bgcolor="#FFFFFF"><img src width=1 height=1></td>

          <td nowrap nowrap>&nbsp; 
            <a class=submnubar href="health4life.htm">Health4Life<br>
            &nbsp;&nbsp;&nbsp;Programme</a><td nowrap nowrap bgcolor="#FFFFFF"><img src width=1 height=1>

          <td nowrap nowrap>&nbsp;
            <a class=submnubar href="guarantee.htm">Product Guarantee<br>
            &nbsp;&nbsp;&nbsp;Registration</a><td bgcolor="#FFFFFF"><img src width=1 height=1></td>

          <td nowrap nowrap>&nbsp;
            <a class=submnubar href="affiliate.htm">Affiliate<br>
            &nbsp;&nbsp;&nbsp;Programme</a><td bgcolor="#FFFFFF"><img src width=1 height=1></td>

          <td nowrap nowrap>&nbsp;
            <a class=submnubar href="faq.htm">Help
            &amp; FAQs</a></td>
        </tr>
      </table>
